Don't allow to process InstallSnapshot and compaction parallelly
lerna-stack/akka-entity-replication pull request #117
Opened 2021-12-29 08:46 UTC by negokaz

Closes #113

2022-01-05 14:27 UTC, tksugimoto commented on src/test/scala/lerna/akka/entityreplication/raft/RaftActorSnapshotSynchronizationSpec.scala
> +          msg.replyTo ! SaveSnapshotSuccess(msg.snapshot.metadata)
```
      snapshotStore.receiveWhile(messages = 2) {
        case msg: SaveSnapshot =>
          msg.replyTo ! SaveSnapshotSuccess(msg.snapshot.metadata)
```

この `2` は どのように導出されますか？

2022-01-05 14:28 UTC, tksugimoto requested changes
レビューしました。

コンフリクト解消お願いします。

> Conflicting files
src/test/scala/lerna/akka/entityreplication/raft/RaftActorSpec.scala

2022-01-06 02:17 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/raft/RaftActorSnapshotSynchronizationSpec.scala
> +          msg.replyTo ! SaveSnapshotSuccess(msg.snapshot.metadata)
@tksugimoto 正しくは `1` でした。修正しました。
f8eedf8b

2022-01-06 07:18 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/raft/RaftActorSnapshotSynchronizationSpec.scala
> +          msg.replyTo ! SaveSnapshotSuccess(msg.snapshot.metadata)
チェックを追加しました。

- 46777467 `🚨test: Inspect number of messages that receiveWhile produces`

`RaftSnapshotStoreTestKit` のテストを実装すると、期待と異なるメッセージが reply された場合、次に `RaftSnapshotStoreTestKit` のメソッドを呼び出したときに `receiveWhile` が即時終了してしまって予期しない結果になる問題が見つかったため `receiveN` を使うように変更しました。

- ee3e3225 `🚨test: Use receiveN instead of receiveWhile in RaftSnapshotStoreTestKit`

2022-01-06 07:54 UTC, tksugimoto approved these changes

2022-01-06 09:52 UTC, merged