WIP: Disabling specific raft actor's launching by its own shard id
lerna-stack/akka-entity-replication pull request #173
Opened 2022-10-05 11:01 UTC by ydash

2022-10-12 08:46 UTC, xirc requested changes
Great!

I left some comments.

As same as `RaftActor`, `CommitLogStoreActor` also should stop itself if its shard ID is disabled. Would it be possible also to change `CommitLogStoreActor`? `CommitLogStoreActor` can use its `shardId` method to get its shard ID.

2022-10-12 08:46 UTC, xirc commented on src/main/scala/lerna/akka/entityreplication/raft/RaftSettings.scala
> +  def disabledShards: Set[String]
`RaftSettings.disabledShards` wants an unit test like `settings.disabledShards shouldBe Set()`. The test can be written [here](
https://github.com/lerna-stack/akka-entity-replication/blob/618a211459d4c3707f29391e6b0bc18897da3629/src/test/scala/lerna/akka/entityreplication/raft/RaftSettingsSpec.scala#L19-L50).

2022-10-12 10:05 UTC, negokaz commented on src/main/resources/reference.conf
> +    disabled-shards = []
@xirc Related settings such as `raft.number-of-shards` and `raft.disabled-shards` should be closer together.
I think it is better to put `raft.disabled-shards` directly below `raft.number-of-shards`.
Moreover, it would be better to explain how related to `raft.number-of-shards` by the comment.

2022-10-19 04:17 UTC, ydash commented on src/main/resources/reference.conf
> +    // Shard Ids of raft actors to disable.
@xirc 

add example

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/aae08439ed32a0c51aa9e24bfc83b784267a1444

2022-10-19 04:18 UTC, ydash commented on src/main/scala/lerna/akka/entityreplication/ReplicationRegion.scala
> +        log.warning(s"Following command had sent to disabled shards was dropped: ${message.getClass.getName}")
@xirc 

add shardId to warn log

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/493389d02bc1f635fcfa5d3aa87a93ff01c387ef

2022-10-19 04:19 UTC, ydash commented on src/main/scala/lerna/akka/entityreplication/ReplicationRegion.scala
> +  private val disabledShards = settings.raftSettings.disabledShards
@xirc 

add the type annotation

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/c655fa22ab1bbb11bbace59edee61b81fb6cddc2

2022-10-19 04:20 UTC, ydash commented on src/main/resources/reference.conf
> +    disabled-shards = []
@xirc 

move `disabled-shards` under `number-of-shards`

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/9c7c04a8506759ee6faf2605df04bdffdcd79835

2022-10-19 04:24 UTC, ydash commented on src/main/scala/lerna/akka/entityreplication/raft/RaftSettings.scala
> +  def disabledShards: Set[String]
@xirc 

add test of `disabledShards` to `RaftSettingsSpec`.

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/2622d6b4efbdda112aae52f58b8b2cd5fecf3a24

2022-10-19 04:54 UTC, ydash commented on src/test/scala/lerna/akka/entityreplication/raft/RaftActorSpec.scala
> +      )
@xirc 

I know there is helper function `createRaftActor`.
But, I think `createRaftActor` can't work in this test. In this test, `createRaftActor` keeps awaiting forever in `awaitCond`. Because disabled shards stop itself and never return `stateName`.

https://github.com/lerna-stack/akka-entity-replication/blob/0acd526ff2dbeb0689b95a69bfaa9b28b519ebd3/src/test/scala/lerna/akka/entityreplication/raft/RaftActorSpecBase.scala#L114

2022-10-19 07:19 UTC, ydash commented
@xirc 

> As same as `RaftActor`, `CommitLogStoreActor` also should stop itself if its shard ID is disabled. Would it be possible also to change `CommitLogStoreActor`? `CommitLogStoreActor` can use its `shardId` method to get its shard ID.

I implemented feature of stopping itself to `CommitLogStoreActor`.

https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/5f8f982ac48afcf453910a621e370b6fe2c0ce24
https://github.com/lerna-stack/akka-entity-replication/pull/173/commits/44e7a8aafba807071918949627a36b87d8538904

2022-10-20 01:03 UTC, xirc commented on src/test/scala/lerna/akka/entityreplication/raft/RaftActorSpec.scala
> +      )
@ydash Thank you. Not using `createRaftActor` makes sense to me.

2022-10-20 06:16 UTC, xirc approved these changes
Great! LGTM 👍

2022-10-20 06:17 UTC, merged