Allow testing ReplicationActor
lerna-stack/akka-entity-replication pull request #23
Opened 2021-03-09 11:31 UTC by negokaz

2021-03-11 10:38 UTC, yugolf requested changes

2021-03-11 10:38 UTC, yugolf commented on README.md
### 文法チェック

>Each replicated entities are distributed

- Eachの後ろは単数形
Each replicated entity is distributed

>availablity

- スペルミス
availability

>The replicas of each entity are not started on every node in the Cluster, but are placed in such a way that the load is distributed by sharding based on Consistent Hash. 

- butの前のカンマは不要
The replicas of each entity are not started on every node in the Cluster but are placed in such a way that the load is distributed by sharding based on Consistent Hash.

2021-03-12 09:09 UTC, negokaz commented on README.md
@yugolf 
↓ で修正しました

https://github.com/lerna-stack/akka-entity-replication/pull/24/commits/ba18f37ec60c160f4795026d82b49926f833ec15

2021-03-12 09:57 UTC, tksugimoto approved these changes

2021-03-12 12:26 UTC, yugolf approved these changes

2021-03-13 01:42 UTC, merged