[Typed] Implementation for ReplicatedEntityBehavior
lerna-stack/akka-entity-replication pull request #64
Opened 2021-04-16 09:44 UTC by negokaz

related issue #44

2021-05-04 10:17 UTC, tksugimoto requested changes

2021-05-06 00:17 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/WaitForReplication.scala
> +    if (command.instanceId.map(_.underlying).contains(state.instanceId.underlying)) {
@tksugimoto `.underlying` を削除しました

8070a4f3

2021-05-06 00:21 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      instanceId = EntityInstanceId(state.instanceId.underlying),
@tksugimoto 直接 state の instanceId をコマンドに設定するようにしました

04bdb0c3

2021-05-06 00:53 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/WaitForReplication.scala
> +    if (command.instanceId.map(_.underlying).contains(state.instanceId.underlying)) {
@tksugimoto 

> Classic版からなのですが、 command.instanceId が None (event == NoOp) の場合は、 applySideEffects しなくて問題ないでしょうか？

`instanceId` が `None` でくることはないので、`require` を追記しました。 f3e04206

Entity が受け取った `ReplicationSucceeded` には常に `instanceId` が含まれているはずです。なぜなら、Entity はこのメッセージと対になる `Replicate` コマンドに常に `instanceId` を設定するからです。

> ```scala
>     setup.shard ! RaftProtocol.Replicate(
>       event = event,
>       replyTo = context.self.toClassic,
>       entityId = setup.replicationId.entityId,
>       instanceId = state.instanceId,
>       originSender = context.system.deadLetters.toClassic, // typed API can not use sender
>     )
> ```
> **[akka-entity-replication/Ready.scala at typed/replicated-entity-behavior-impl · lerna-stack/akka-entity-replication](https://github.com/lerna-stack/akka-entity-replication/blob/f3e04206bd878dfb1214288eab9b80a72e075987/src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala#L118-L124)**

`RaftActor` に返される `ReplicationSucceeded` の `instanceId` のみが `None` になります。

> ```scala
>   private[this] def receiveReplicationResponse(event: ReplicationResponse): Unit =
>     event match {
> 
>       case ReplicationSucceeded(NoOp, _, _) =>
>       // ignore: no-op replication when become leader
> 
>       case ReplicationSucceeded(unknownEvent, _, _) =>
>         log.warning("unknown event: {}", unknownEvent)
>     }
> ```
> **[akka-entity-replication/Leader.scala at typed/replicated-entity-behavior-impl · lerna-stack/akka-entity-replication](https://github.com/lerna-stack/akka-entity-replication/blob/f3e04206bd878dfb1214288eab9b80a72e075987/src/main/scala/lerna/akka/entityreplication/raft/Leader.scala#L201-L209)**

2021-05-06 01:01 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/typed/ReplicatedEntityBehaviorSpec.scala
> +            instanceId should not be null
@tksugimoto 

このケースでは何かしら `instanceId` に値が設定されていることが確認できていればよいので、 `instanceId should not be empty`  に修正しました。

224692c3

2021-05-06 01:19 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Recovering.scala
> +            // TODO: Enable backoff to prevent cascade failures
@tksugimoto 

issue にしました #72

2021-05-06 03:18 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicatedEntityBehaviorImpl.scala
> +  def createBehavior(shard: ActorRef[ShardCommand], settings: ClusterReplicationSettings): Behavior[EntityCommand] = {
> `def interceptor`
> `def createBehavior`

mimaも入れましたし、外から呼ばれないならば、 `private` にしておいたほうが良いと思います。

2021-05-06 03:20 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicatedEntityBehaviorImpl.scala
> +  def createBehavior(shard: ActorRef[ShardCommand], settings: ClusterReplicationSettings): Behavior[EntityCommand] = {
class側で private になってましたね

> `private[entityreplication] final case class ReplicatedEntityBehaviorImpl`

package private を無視する mimaも 0.9リリースされてました。

[Release 0.9.0 · lightbend/mima](https://github.com/lightbend/mima/releases/tag/0.9.0)

> Ignore package private classes

2021-05-06 03:39 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +        throw new IllegalStateException(s"Illegal effect Implementation: ${other.getClass.getName}") // TODO:
>         throw new IllegalStateException(s"Illegal effect Implementation: ${other.getClass.getName}") // TODO:

何を TODO でしょうか？

2021-05-06 03:53 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/BehaviorSetup.scala
> +    signalHandler: PartialFunction[(State, Signal), Unit],
>     signalHandler: PartialFunction[(State, Signal), Unit],

これは現在使用されていませんが、別PRで使われるようになりますか？

2021-05-06 03:57 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicatedEntityBehaviorImpl.scala
> +    copy(signalHandler = signalHandler)
>     copy(signalHandler = signalHandler)

`signalHandler` の上書きですが、`createBehavior` の実行タイミングの都合で上書きが反映されない気がします。

 `BehaviorSetup`  に `signalHandler` が保存されていますが、これは、 `createBehavior` の中で行われており、`apply` した瞬間に確定しているように見えます。

```scala
  override def apply(ctx: TypedActorContext[Command]): Behavior[Command] = {
    try {
      val settings = ClusterReplicationSettings(ctx.asScala.system.toClassic)
      Behaviors.intercept(() => interceptor)(createBehavior(entityContext.shard, settings)).narrow
```
※ 名前渡しではなかったです。

```scala
def intercept[O, I](behaviorInterceptor: () => BehaviorInterceptor[O, I])(behavior: Behavior[I]): Behavior[O]
```

2021-05-06 04:07 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicatedEntityBehaviorImpl.scala
> +    copy(signalHandler = signalHandler)
object の apply と class の apply を間違えていたので、問題なかったです。

`EventSourcedBehaviorImpl` も同様の実装でした。

[akka/EventSourcedBehaviorImpl.scala at v2.6.14 · akka/akka](https://github.com/akka/akka/blob/v2.6.14/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala#L85-L113)

2021-05-06 04:58 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +        throw new IllegalStateException(s"Illegal effect Implementation: ${other.getClass.getName}") // TODO:
@tksugimoto コメントの消し忘れでした

5841ca1d

2021-05-06 06:23 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/BehaviorSetup.scala
> +    signalHandler: PartialFunction[(State, Signal), Unit],
@tksugimoto すみません、実装し忘れです。

次のコミットで実装しました。

- b3de1ab7
- 2c0cd13d

2021-05-06 07:18 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
機能的には問題ないですが、いくつかは 内部で書き換わることがないので ReadyState に入れるのではなく、 `class Ready` のプロパティとして定義したほうが分かりやすいと思いました。

```scala
  final case class ReadyState[State](
      entityState: State,
      instanceId: InstanceId,
      lastAppliedLogEntryIndex: LogEntryIndex,
      stashBuffer: StashBuffer[EntityCommand],
```

- instanceId
- stashBuffer

2021-05-06 07:51 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/BehaviorSetup.scala
> +    signalHandler: PartialFunction[(State, Signal), Unit],
```scala
    case _ =>
      Behaviors.unhandled
```
でその他すべてを受け取っても問題ないですか？

Akka 内部では、 `MessageAdaptionFailure` の場合、 unhandled じゃない処理が行われるようですが、これをskipしてしまうように見えます。


```
    override def receiveSignal(ctx: AC[T], msg: Signal): Behavior[T] = {
      onSignal.applyOrElse(
        (ctx.asScala, msg),
        BehaviorImpl.unhandledSignal.asInstanceOf[PartialFunction[(SAC[T], Signal), Behavior[T]]])
    }
```
```scala
  val unhandledSignal: PartialFunction[(TypedActorContext[Nothing], Signal), Behavior[Nothing]] = {
    case (_, MessageAdaptionFailure(ex)) => throw ex
    case (_, _)                          => UnhandledBehavior
  }
```

2021-05-06 08:22 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
@tksugimoto 個人的には `Behavior` が持つ状態は State にまとまっていたほうがわかりやすいと思います。

特に `stashBuffer` は確かに参照の更新はされないですが、mutable な状態です。なので `entityState` などと同じように扱うのが適切だと思います。

2021-05-06 08:22 UTC, tksugimoto requested changes

2021-05-06 08:22 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Recovering.scala
> +          case _: RaftProtocol.ReplicationSucceeded => Behaviors.unhandled
>           case _: RaftProtocol.ReplicationSucceeded => Behaviors.unhandled

Classic版は stash ですが、変わって問題ないですか？

```scala
        case _ =>
          internalStash.stash()
```

2021-05-06 08:22 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +          )
```
      event match {
        case NoOp =>
          copy(
            lastAppliedLogEntryIndex = logEntryIndex,
          )
```

Classic側は、 NoOp 分岐がなくて、 warn ログが出る問題が残っていますよね？

忘れないようにIssueにしておきましょう。

2021-05-06 08:22 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        throw new IllegalArgumentException(s"Unsupported side effect found: $effect")
```scala
      case _ =>
        throw new IllegalArgumentException(s"Unsupported side effect found: $effect")
```


- `NoReplyEffect` と `UnhandledEffect` はなぜサポートされていないですか？コメントがあると良いと思います。
- `_` でまとめないほうが良いと思います
  -  何がサポートされていないのか分かりやすい
  - (将来の変更時) compile チェックされる

2021-05-06 08:32 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Recovering.scala
> +          case _: RaftProtocol.ReplicationSucceeded => Behaviors.unhandled
@tksugimoto 

Entity が受け入れる `ReplicationSucceeded` は `instanceId` が一致するもののみですが、`Recovering` の時点でそれが送られてくることはありえないので、問題ないです。`instanceId` が古いものが送られてくる可能性はありますが、最終的にそれは処理せず捨てないといけません。

2021-05-06 08:32 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
```scala
      case _: UnstashAllEffect[_] =>
        stashBuffer.unstashAll(behavior)
        behavior
```
`unstashAll` は `Behavior` を返しますが、握りつぶして問題ないですか？

```scala
def unstashAll(behavior: Behavior[T]): Behavior[T]
```

2021-05-06 08:39 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
> 特に stashBuffer は確かに参照の更新はされないですが、mutable な状態です。なので entityState などと同じように扱うのが適切だと思います。

mutable ならばこそ entityState などと同じように扱うべきではないと思います。

- `def` のプロパティにわたすのは、Classic Actor での `var` での定義の代わり
- class のプロパティにわたすのは、Classic Actor での `val` での定義の代わり

と考えられるので、 mutable + var は避けるべきだと思います。

[Zen of Akka](https://www.slideshare.net/ktoso/zen-of-akka/37)

![image](https://user-images.githubusercontent.com/13145001/117267392-2dfd5480-ae91-11eb-9eb6-60a3ae4e0f2e.png)

2021-05-06 08:58 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Recovering.scala
> +          case _: RaftProtocol.ReplicationSucceeded => Behaviors.unhandled
Classic版では ready の unhandled に流れるようになっていますね。
```scala
case other => ReplicationActor.super.aroundReceive(receive, other)
```

タイミングは違うけど大きな問題ではないと理解しました。

2021-05-06 10:05 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      originSender = context.system.deadLetters.toClassic, // typed API can not use sender
[nits]

> originSender = context.system.deadLetters.toClassic, // typed API can not use sender

`Actor.noSender` or `ActorRef.noSender` を使うとシンプルだと思います。

2021-05-07 01:05 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      originSender = context.system.deadLetters.toClassic, // typed API can not use sender
@tksugimoto 

NPE が発生するリスクを避けるため、`noSender` を使わないようにしていました。

2021-05-07 02:13 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      originSender = context.system.deadLetters.toClassic, // typed API can not use sender
> NPE が発生するリスクを避けるため、noSender を使わないようにしていました。

なるほど、その旨がコメントで書いてあると理解しやすかったです。

ちなみに、method 呼び出しのレシーバーとしては使用されず、 tell() の sender として使用されるので、現在の実装では NPEにはならなかったです。

2021-05-07 05:34 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        throw new IllegalArgumentException(s"Unsupported side effect found: $effect")
@tksugimoto なぜこのような実装になっていたのか思い出せなかったですが、実装しない理由はないと考え実装しました。

- e0647087
- 1342fb49
- 424fb928

Unhandled を使ったときに Behavior 内部で例外が発生するのでこの指摘は MUST かもしれません。

2021-05-07 05:51 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
@tksugimoto 

公式ドキュメントの例では握りつぶしてないので、握りつぶさないほうが良さそうです。

> ```scala
>       case InitialState(value) =>
>         // now we are ready to handle stashed messages if any
>         buffer.unstashAll(active(value))
> ``` 
> 
> **[Stash • Akka Documentation](https://doc.akka.io/docs/akka/2.6/typed/stash.html#:~:text=case%20InitialState,(value)))**

2021-05-07 06:06 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
@tksugimoto Behavior を握りつぶさないように修正しました。

- 544d316d

また、内部 API の `StashBuffer.apply` を使わなくても `Behaviors.withStash` で `StashBuffer` が使えることがわかったので、`Behaviors.withStash` を使うように修正しました。

- 0c9d539e

2021-05-07 06:22 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +          )
@tksugimoto #76 に起票しました。

2021-05-07 06:35 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/BehaviorSetup.scala
> +    signalHandler: PartialFunction[(State, Signal), Unit],
@tksugimoto 確かに。その case は消したほうが良さそうですね。

2021-05-07 06:41 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
IMO

```
      case _: NoReplyEffect[_] =>
        behavior
```

[✨feat: Use NoReplyEffect](https://github.com/lerna-stack/akka-entity-replication/commit/424fb9286fc0eefefa6eed3ad2c307047e178dd3)

そもそも、 NoReplyEffect がいらないのではないでしょうか？

2021-05-07 06:41 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +          UnhandledMessage(command.command, setup.context.system.toClassic.deadLetters, setup.context.self.toClassic)
IMO

> Message(command.command, setup.context.system.toClassic.deadLetters, setup.context.self.toClassic)

ここは、 NPE のリスクもないですし `ActorRef.noSender` を使うべきだと思います。

deadLetters を使うと、DeadLetter の ログ出力で誤解が生まれやすいと思います。

`akka.event.DeadLetterListener`
```scala
  private def logDeadLetter(d: AllDeadLetters, doneMsg: String): Unit = {
    val origin = if (isReal(d.sender)) s" from ${d.sender}" else ""
```
```scala
  private def isReal(snd: ActorRef): Boolean = {
    (snd ne ActorRef.noSender) && (snd ne context.system.deadLetters) && !snd.isInstanceOf[DeadLetterActorRef]
  }
```

2021-05-07 06:42 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/BehaviorSetup.scala
> +    signalHandler: PartialFunction[(State, Signal), Unit],
@tksugimoto 

`case _ =>` を消しました

fcfeffc0

2021-05-07 06:49 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
@tksugimoto 

> そもそも、 NoReplyEffect がいらないのではないでしょうか？

それは考えましたが、デバッグするときに `NoReply` が明示的に見えたほうがわかりやすいと思い残しました。

ちなみに `EventSourcedBehavior` の実装にも `NoReplyEffectImpl` があります。

> ```scala
> /** INTERNAL API */
> @InternalApi
> final private[akka] class NoReplyEffectImpl[State] extends Callback[State](_ => ()) {
>   override def toString: String = "NoReply"
> }
> ```
> **[akka/SideEffect.scala at master · akka/akka](https://github.com/akka/akka/blob/v2.6.13/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/SideEffect.scala#L36-L40)**

2021-05-07 06:58 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +        behavior
> それは考えましたが、デバッグするときに NoReply が明示的に見えたほうがわかりやすいと思い残しました。

🆗 

> final private[akka] class NoReplyEffectImpl[State] extends Callback[State](_ => ()) {

EventSourcedBehavior  は NoReply も `Callback` なのですね。

2021-05-07 07:09 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +          UnhandledMessage(command.command, setup.context.system.toClassic.deadLetters, setup.context.self.toClassic)
@tksugimoto
 
`origin` に deadLetters が出てしまうという指摘でしょうか？
`isReal` の `(snd ne context.system.deadLetters)` の条件によって origin は空文字になりそうです。

ちなみに `EventSourcedBehavior` でも sender を deadLetters にする同様の実装でした。

> ```scala
>         case _: Unhandled.type =>
>           import akka.actor.typed.scaladsl.adapter._
>           setup.context.system.toClassic.eventStream
>             .publish(UnhandledMessage(msg, setup.context.system.toClassic.deadLetters, setup.context.self.toClassic))
>           (applySideEffects(sideEffects, state), true)
> ```
> **[akka/Running.scala at v2.6.14 · akka/akka](https://github.com/akka/akka/blob/v2.6.14/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala#L590-L594)**

2021-05-07 07:11 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/ReplicationOperations.scala
> +          UnhandledMessage(command.command, setup.context.system.toClassic.deadLetters, setup.context.self.toClassic)
> isReal の (snd ne context.system.deadLetters) の条件によって origin は空文字になりそうです。

確かに。

取り下げます。

2021-05-07 07:26 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
@tksugimoto なるほど。インスタンスの入れ替わりがないことをコードで表現したほうが良いということですね。

class のプロパティも状態遷移の際にインスタンスを入れ替えることができるので、`var` か `val` かというと、`var` にあたりそうな気がしました。

より `val` に近いのは、`BehaviorSetup` かなと思いました。`BehaviorSetup` は Actor が生きている間ずっと同じインスタンスを引き回すので。

2021-05-07 08:14 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
> インスタンスの入れ替わりがないことをコードで表現したほうが良いということですね。

YES. 読むのが大変でした。

> class のプロパティも状態遷移の際にインスタンスを入れ替えることができるので、var か val かでいうと、var にあたりそうな気がしました。

そこは、 classのプロパティと`def` のプロパティで使い分ける(暗黙の?)ルールがあると思っています。
「Scala で `null` は使わない」みたいな感じ。

実際、現状 class を new し直していることはないです。

`BehaviorSetup` に入れても良いです。

（※ BehaviorSetup に入れても入れ替えることは可能なので、確実なものは無いと思います）

2021-05-07 08:33 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/behavior/Ready.scala
> +      stashBuffer: StashBuffer[EntityCommand],
@tksugimoto `instanceId` と `stashBuffer` を `BehaviorSetup` に移動しました。

- af6b0232
- 6d3b8b59

2021-05-07 08:44 UTC, tksugimoto approved these changes

2021-05-07 08:48 UTC, merged