[Typed] Implement ClusterReplication
lerna-stack/akka-entity-replication pull request #66
Opened 2021-04-19 10:18 UTC by negokaz

related issue: #44

2021-05-13 00:56 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/typed/ClusterReplicationSpec.scala
> +    val region = clusterReplication.init(entity)
This line thorows:
```
[info]   java.lang.UnsupportedOperationException: cannot create top-level actor [replicationRegion-GetEntityContext] from the outside on ActorSystem with custom user guardian
[info]   at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:895)
[info]   at lerna.akka.entityreplication.ClusterReplication.internalStart(ClusterReplication.scala:48)
[info]   at lerna.akka.entityreplication.typed.internal.ClusterReplicationImpl.internalInit(ClusterReplicationImpl.scala:65)
[info]   at lerna.akka.entityreplication.typed.internal.ClusterReplicationImpl.$anonfun$init$1(ClusterReplicationImpl.scala:23)
[info]   at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:99)
[info]   at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:96)
[info]   at scala.collection.convert.JavaCollectionWrappers$JConcurrentMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:403)
[info]   at lerna.akka.entityreplication.typed.internal.ClusterReplicationImpl.init(ClusterReplicationImpl.scala:23)
[info]   at lerna.akka.entityreplication.typed.ClusterReplicationSpec.$anonfun$new$1(ClusterReplicationSpec.scala:42)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

2021-05-13 06:30 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/typed/ClusterReplicationSpec.scala
> +    val region = clusterReplication.init(entity)
resolved with e45c76c

2021-05-18 10:06 UTC, tksugimoto requested changes

2021-05-19 09:01 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/model/NormalizedEntityId.scala
> +  def decoded: String = URLDecoder.decode(underlying, ByteString.UTF_8)
@tksugimoto `Normalized` （何かしら正規化されていて元の ID とは違うもの）に対しての `decoded` というイメージでした。

2021-05-19 09:17 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/model/NormalizedEntityId.scala
> +  def decoded: String = URLDecoder.decode(underlying, ByteString.UTF_8)
`NormalizedShardId` だと 同じ意味のmethodが `raw` なので統一しておいたほうが良いと思います。
```scala
private[entityreplication] final case class NormalizedShardId private (underlying: String) extends AnyVal {
  def raw: String = URLDecoder.decode(underlying, "utf-8")
}
```

2021-05-21 09:23 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/model/NormalizedEntityId.scala
> +  def decoded: String = URLDecoder.decode(underlying, ByteString.UTF_8)
@tksugimoto リネームしました 9d5864f1

2021-05-21 09:23 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/model/NormalizedEntityId.scala
> +  def decoded: String = URLDecoder.decode(underlying, ByteString.UTF_8)
@tksugimoto `EntityId` を使うようにしました 9d5864f1

2021-05-21 09:24 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/ClusterReplicationImpl.scala
> +        (Math.abs(entityId.hashCode) % settings.raftSettings.numberOfShards).toString
@tksugimoto `abs` の前に剰余計算するようにしました efc72b0d

2021-05-21 10:22 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/ClusterReplicationImpl.scala
> +    regions.getOrElseUpdate(entity.typeKey, internalInit(entity)).toTyped
@tksugimoto Region 作成が衝突するのを回避するための `ClusterReplicationGuardian` を作りました 7d7cb92c

2021-05-24 04:50 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/ClusterReplicationImpl.scala
> +    regions.getOrElseUpdate(entity.typeKey, internalInit(entity)).toTyped
> ClusterReplicationGuardian 

概ね良さそうです。

> `val regionName = ActorIds.actorName("replicationRegion", typeName)`

`ActorIds.actorName` を使うように変更されていますが使わないほうが良いと思います。

1. 元々 `s"$actorNamePrefix-$typeName"` にしていたのは、同じ階層にActorが多かったからですが、この変更で間に `clusterReplicationGuardian` が入るようになったので不要
2. `ActorIds.actorName` だと `:` が入っているとNGなので、 v1 と動きが変わってしまっている。(actor nameに使用できない文字があるとエラーだが元々なのでこのPRでは目をつむる)

----

よく考えたら、同時呼び出し問題は v1 でも発生していたので、別PRにしたほうが良いですね。
ちょうど最新commitなので、分離して、このPRは1つ戻してforce pushしました。

`fix/avoid-region-creation-collisions`

[Comparing typed/cluster-replication-impl...fix/avoid-region-creation-collisions · lerna-stack/akka-entity-replication](https://github.com/lerna-stack/akka-entity-replication/compare/typed/cluster-replication-impl...fix/avoid-region-creation-collisions?expand=1)

2021-05-24 07:13 UTC, tksugimoto approved these changes

2021-05-24 10:02 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/ClusterReplicationImpl.scala
> +    regions.getOrElseUpdate(entity.typeKey, internalInit(entity)).toTyped
@tksugimoto 

> ActorIds.actorName だと : が入っているとNGなので、 v1 と動きが変わってしまっている。(actor nameに使用できない文字があるとエラーだが元々なのでこのPRでは目をつむる)

URLエンコードされた `TypeName.underlying` を使うようにしました。
これにより `:` は別の文字に変換されるので、TypeName に `:` 含めたとしてもエラーにはならないはずです。

50271c75fe936f42c1250bf6b5f29c3cf8847440

2021-05-26 05:11 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/typed/internal/ClusterReplicationImpl.scala
> +    regions.getOrElseUpdate(entity.typeKey, internalInit(entity)).toTyped
続きは作成されたPRで。

https://github.com/lerna-stack/akka-entity-replication/pull/80

2021-05-26 06:37 UTC, tksugimoto submitted a review, later dismissed

2021-05-26 07:16 UTC, tksugimoto commented
force push で 1 commit を 消したら CIが途中で止まってしまったようです。

> ScalaTest Report Expected — Waiting for status to be reported

re-run できそうなところやってみましたが変わらず。

最新commitを `git commit --amend` して 時刻だけ変わった状態で また force pushでしょうか？

2021-05-27 02:39 UTC, negokaz commented
@tksugimoto CI がパスしました。Approve お願いします。

2021-05-27 03:06 UTC, tksugimoto approved these changes

2021-05-27 03:06 UTC, merged