[Typed] Implement AtLeastOnceComplete.askTo
lerna-stack/akka-entity-replication pull request #68
Opened 2021-04-20 06:09 UTC by negokaz

related issue: #44

2021-05-10 08:52 UTC, tksugimoto requested changes

2021-05-10 08:52 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +  private[this] def internalAskTo[Message, Reply](
[MUST]

> internalAskTo[Message, Reply]

型パラメータ `Message` は未使用です。削除しましょう。

2021-05-10 08:52 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +            "Destination {} did not reply to a message in {}. Retrying to send the message [{}].",
IMO

```
          logging.debug(
            "Destination {} did not reply to a message in {}. Retrying to send the message [{}].",
```

debug 出力のために複雑になりすぎている気がするので、どれか妥協しても良いかもしれません

- debug 出力を諦める
- debug 出力はするが、情報を減らす
- debug 出力をするが、必要な情報を internalAskTo の引数に追加する(機能的には無駄)

2021-05-10 08:52 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +    def apply(retrying: Boolean, logging: LoggingAdapter): Future[Reply]
IMO

>     def apply(retrying: Boolean, logging: LoggingAdapter): Future[Reply]

`logging` は  `def internalAskTo` の中で作る必要はないので、減らしてシンプルにすることが可能です。

2021-05-10 08:52 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
>        destination: RecipientRef[Message],
```scala
    * The returned Future will be completed with an [[akka.pattern.AskTimeoutException]] after the given timeout has expired.
    * The Future will also failed if a [[akka.pattern.StatusReply.Error]] arrives.
    */
  def askWithStatusTo[Message, Reply](
      destination: RecipientRef[Message],
```
ついでにコメント改善しましょう。

https://github.com/lerna-stack/akka-entity-replication/pull/71#discussion_r623754894

2021-05-11 00:44 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +  private[this] def internalAskTo[Message, Reply](
@tksugimoto 型パラメータ `Message` を削除しました

c273f3a

2021-05-11 01:04 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +            "Destination {} did not reply to a message in {}. Retrying to send the message [{}].",
@tksugimoto リトライが起きるということは、リトライ間隔が短すぎたりクラスターが不安定になっていたり、何らかの問題が起きていると言えると思うので、debug レベルではなく warning レベルに変更しました。

0045566

> debug 出力をするが、必要な情報を internalAskTo の引数に追加する(機能的には無駄)

これは `internalAskTo` でログ出力を共通化するということでしょうか？
であれば、Typed 版では message を取り出すのに `replyTo` 用の `ActorRef` が必要なので難しい気がしています。
問題を分析する際にどの処理が不調なのかを明らかにするのにメッセージの種別は特定できたほうが良いと思うので、情報を落とすというのもできれば避けたいと思っています。

2021-05-11 04:06 UTC, tksugimoto commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
> +            "Destination {} did not reply to a message in {}. Retrying to send the message [{}].",
> リトライが起きるということは、リトライ間隔が短すぎたりクラスターが不安定になっていたり、何らかの問題が起きていると言えると思うので、debug レベルではなく warning レベルに変更しました。

👌 

> これは internalAskTo でログ出力を共通化するということでしょうか？


そういう意味でした。

> であれば、Typed 版では message を取り出すのに replyTo 用の ActorRef が必要なので難しい気がしています。


確かに！
取り下げます。

2021-05-11 05:08 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/util/AtLeastOnceComplete.scala
>        destination: RecipientRef[Message],
@tksugimoto 説明を修正しました。

c28823c

2021-05-11 06:11 UTC, tksugimoto approved these changes

2021-05-11 06:11 UTC, merged