[Typed] Implement ReplicatedEntityBehaviorTetstkit
lerna-stack/akka-entity-replication pull request #69
Opened 2021-04-20 10:30 UTC by negokaz

related issue: #44

2021-05-12 09:56 UTC, tksugimoto requested changes

2021-05-13 00:09 UTC, negokaz commented on src/test/scala/lerna/akka/entityreplication/typed/testkit/ReplicatedEntityBehaviorTestKitSpec.scala
> +      commandResult.state
@tksugimoto アサーションを追加しました

482dc11

2021-05-13 00:31 UTC, negokaz commented on src/main/scala/lerna/akka/entityreplication/typed/internal/testkit/ReplicatedEntityBehaviorTestKitImpl.scala
> +        throw new AssertionError(s"$objCategory [$obj] isn't serializable", ex)
@tksugimoto 原因によって対処が変わるので、一概にこの対処をしてくださいと言うのが難しい気がします。スタックトレースに出る cause をヒントに対処してもらうのが良いのではないでしょうか？

```
[info]   java.lang.AssertionError: Reply [UnserializableReply()] isn't serializable
[info]   at lerna.akka.entityreplication.typed.internal.testkit.ReplicatedEntityBehaviorTestKitImpl.verifySerialization(ReplicatedEntityBehaviorTestKitImpl.scala:152)
[info]   at lerna.akka.entityreplication.typed.internal.testkit.ReplicatedEntityBehaviorTestKitImpl.$anonfun$verifyPostRunCommand$2(ReplicatedEntityBehaviorTestKitImpl.scala:144)
[info]   at lerna.akka.entityreplication.typed.internal.testkit.ReplicatedEntityBehaviorTestKitImpl.$anonfun$verifyPostRunCommand$2$adapted(ReplicatedEntityBehaviorTestKitImpl.scala:144)
[info]   at scala.Option.foreach(Option.scala:437)
[info]   at lerna.akka.entityreplication.typed.internal.testkit.ReplicatedEntityBehaviorTestKitImpl.verifyPostRunCommand(ReplicatedEntityBehaviorTestKitImpl.scala:144)
[info]   at lerna.akka.entityreplication.typed.internal.testkit.ReplicatedEntityBehaviorTestKitImpl.runCommand(ReplicatedEntityBehaviorTestKitImpl.scala:71)
[info]   at lerna.akka.entityreplication.typed.testkit.ReplicatedEntityBehaviorTestKitSpec.$anonfun$new$12(ReplicatedEntityBehaviorTestKitSpec.scala:83)
[info]   at org.scalatest.Assertions.intercept(Assertions.scala:807)
[info]   at org.scalatest.Assertions.intercept$(Assertions.scala:804)
[info]   at org.scalatest.FlatSpec.intercept(FlatSpec.scala:1685)
[info]   ...
[info]   Cause: akka.serialization.DisabledJavaSerializer$JavaSerializationException: Attempted to serialize message using Java serialization while `akka.actor.allow-java-serialization` was disabled. Check WARNING logs for more details.
[info]   ...
```

2021-05-13 02:23 UTC, tksugimoto approved these changes

2021-05-13 02:23 UTC, merged